# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build-wasm:
    name: Build the source code into WASM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          sudo apt install libtool-bin intltool autoconf-archive
          # install make 4.3 to get grouped targets functionality
          curl http://archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.3-4ubuntu1_amd64.deb -OL
          sudo dpkg -i make_4.3-4ubuntu1_amd64.deb

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: build/release
          key: $${{ hashFiles('Makefile') }}

      - name: Build code
        run: make deploy -j$(nproc) RELEASE=1

      - name: list files
        run: ls -al

      - name: list files
        run: ls -al ./build
